# Generated by Django 2.0.3 on 2018-03-14 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgeText', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppearanceText', models.CharField(max_length=25)),
                ('Probability', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GenderText', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Cost', models.IntegerField(default=0)),
                ('Notes', models.CharField(max_length=100)),
                ('Attunement', models.BooleanField(default=False)),
                ('Rarity', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ItemEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name1', models.CharField(max_length=15)),
                ('Name2', models.CharField(max_length=15)),
                ('Effect', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameText', models.CharField(max_length=25)),
                ('Position', models.IntegerField(default=0)),
                ('Gender', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='Towns.Gender')),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='Towns.Age')),
                ('Appearance', models.ManyToManyField(to='Towns.Appearance')),
                ('FirstName', models.ManyToManyField(related_name='_npc_FirstName_+', to='Towns.Name')),
                ('Gender', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='Towns.Gender')),
                ('LastName', models.ManyToManyField(related_name='_npc_LastName_+', to='Towns.Name')),
            ],
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PersonalityText', models.CharField(max_length=25)),
                ('Probability', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RaceText', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Balance', models.IntegerField(default=0)),
                ('Name', models.CharField(max_length=40)),
                ('Inventory', models.ManyToManyField(to='Towns.Item')),
                ('Owner', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='Towns.NPC')),
            ],
        ),
        migrations.CreateModel(
            name='ShopName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.IntegerField(default=0)),
                ('NameText', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ShopType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Residents', models.ManyToManyField(to='Towns.NPC')),
                ('Shops', models.ManyToManyField(to='Towns.Shop')),
            ],
        ),
        migrations.AddField(
            model_name='shopname',
            name='Type',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='Towns.ShopType'),
        ),
        migrations.AddField(
            model_name='npc',
            name='Personality',
            field=models.ManyToManyField(to='Towns.Personality'),
        ),
        migrations.AddField(
            model_name='npc',
            name='Race',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='Towns.Race'),
        ),
        migrations.AddField(
            model_name='name',
            name='Race',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='Towns.Race'),
        ),
        migrations.AddField(
            model_name='itemeffect',
            name='Type',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='Towns.ItemType'),
        ),
        migrations.AddField(
            model_name='item',
            name='Effect',
            field=models.ManyToManyField(to='Towns.ItemEffect'),
        ),
        migrations.AddField(
            model_name='item',
            name='Type',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='Towns.ItemType'),
        ),
    ]
