# Generated by Django 2.0.3 on 2018-03-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Towns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age',
            name='AgeText',
            field=models.CharField(max_length=30),
        ),
    ]
