# Generated by Django 2.0.3 on 2018-03-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Towns', '0002_auto_20180314_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemeffect',
            name='Type',
        ),
        migrations.AddField(
            model_name='itemeffect',
            name='Type',
            field=models.ManyToManyField(to='Towns.ItemType'),
        ),
    ]
