# Generated by Django 2.0.3 on 2018-03-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Towns', '0004_itemtype_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopname',
            name='NameText',
            field=models.CharField(max_length=25),
        ),
    ]
