# Generated by Django 2.0.3 on 2018-03-15 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Towns', '0006_auto_20180314_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='Name',
        ),
        migrations.AddField(
            model_name='shop',
            name='FirstName',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='FirstName', to='Towns.ShopName'),
        ),
        migrations.AddField(
            model_name='shop',
            name='LastName',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='LastName', to='Towns.ShopName'),
        ),
        migrations.RemoveField(
            model_name='npc',
            name='FirstName',
        ),
        migrations.AddField(
            model_name='npc',
            name='FirstName',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='FirstName', to='Towns.Name'),
        ),
        migrations.RemoveField(
            model_name='npc',
            name='LastName',
        ),
        migrations.AddField(
            model_name='npc',
            name='LastName',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='LastName', to='Towns.Name'),
        ),
    ]
