# Generated by Django 2.0.3 on 2018-03-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Towns', '0007_auto_20180314_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='Name',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
