# Generated by Django 2.0.3 on 2018-03-20 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Towns', '0008_town_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='Type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='Towns.ShopType'),
        ),
    ]
